"""Init7

Revision ID: 15f3b426f90d
Revises: bfd605422d40
Create Date: 2023-07-26 23:19:47.024858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f3b426f90d'
down_revision = 'bfd605422d40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
