"""Init3

Revision ID: 22062482e045
Revises: c5200c2c74aa
Create Date: 2023-07-26 09:35:00.175662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22062482e045'
down_revision = 'c5200c2c74aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformated_images_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('secure_url', sa.String(length=300), nullable=True),
    sa.Column('transformation_url', sa.String(length=300), nullable=True),
    sa.Column('radius', sa.Integer(), nullable=False),
    sa.Column('effect', sa.String(length=50), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('gravity', sa.String(length=50), nullable=False),
    sa.Column('crop', sa.String(length=50), nullable=False),
    sa.Column('color_space', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformated_images_settings_secure_url'), 'transformated_images_settings', ['secure_url'], unique=True)
    op.create_index(op.f('ix_transformated_images_settings_transformation_url'), 'transformated_images_settings', ['transformation_url'], unique=True)
    op.create_index(op.f('ix_transformated_images_settings_url'), 'transformated_images_settings', ['url'], unique=True)
    op.add_column('users', sa.Column('access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access')
    op.drop_index(op.f('ix_transformated_images_settings_url'), table_name='transformated_images_settings')
    op.drop_index(op.f('ix_transformated_images_settings_transformation_url'), table_name='transformated_images_settings')
    op.drop_index(op.f('ix_transformated_images_settings_secure_url'), table_name='transformated_images_settings')
    op.drop_table('transformated_images_settings')
    # ### end Alembic commands ###
