"""'roles'

Revision ID: 27705af4bc29
Revises: d9088622077f
Create Date: 2023-07-20 11:22:12.715791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27705af4bc29'
down_revision = 'd9088622077f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM('admin', 'moderator', 'user')")
    op.add_column('users', sa.Column('roles', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True, default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE role")
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
