"""Init8

Revision ID: 440a28263794
Revises: 4df0bf0ff5f5
Create Date: 2023-08-01 11:27:44.251967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440a28263794'
down_revision = '4df0bf0ff5f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_message', sa.String(length=500), nullable=True),
    sa.Column('reciever', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
