"""Init6

Revision ID: 4a346f4d4674
Revises: a08398fa3c87
Create Date: 2023-07-30 07:59:54.935960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a346f4d4674'
down_revision = 'a08398fa3c87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
