"""Init9

Revision ID: 6976e207458d
Revises: 440a28263794
Create Date: 2023-08-01 11:33:40.339785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6976e207458d'
down_revision = '440a28263794'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender')
    # ### end Alembic commands ###
