"""Init4

Revision ID: 86783f845e07
Revises: 22062482e045
Create Date: 2023-07-26 14:33:56.961105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86783f845e07'
down_revision = '22062482e045'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformated_images_settings', sa.Column('angle', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transformated_images_settings', 'angle')
    # ### end Alembic commands ###
