"""Init11

Revision ID: 8925401b40df
Revises: fc80aab956f9
Create Date: 2023-07-27 20:46:36.120583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8925401b40df'
down_revision = 'fc80aab956f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformated_images_settings', sa.Column('transformed_url', sa.String(length=300), nullable=True))
    op.add_column('transformated_images_settings', sa.Column('qrcode_url', sa.String(length=300), nullable=True))
    op.drop_index('ix_transformated_images_settings_transformation_url', table_name='transformated_images_settings')
    op.create_index(op.f('ix_transformated_images_settings_qrcode_url'), 'transformated_images_settings', ['qrcode_url'], unique=True)
    op.create_index(op.f('ix_transformated_images_settings_transformed_url'), 'transformated_images_settings', ['transformed_url'], unique=True)
    op.drop_column('transformated_images_settings', 'transformation_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformated_images_settings', sa.Column('transformation_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_transformated_images_settings_transformed_url'), table_name='transformated_images_settings')
    op.drop_index(op.f('ix_transformated_images_settings_qrcode_url'), table_name='transformated_images_settings')
    op.create_index('ix_transformated_images_settings_transformation_url', 'transformated_images_settings', ['transformation_url'], unique=False)
    op.drop_column('transformated_images_settings', 'qrcode_url')
    op.drop_column('transformated_images_settings', 'transformed_url')
    # ### end Alembic commands ###
