"""Init5

Revision ID: a08398fa3c87
Revises: d861face407d
Create Date: 2023-07-30 07:56:53.120645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08398fa3c87'
down_revision = 'd861face407d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transformated_images_settings_qrcode_url', table_name='transformated_images_settings')
    op.create_index(op.f('ix_transformated_images_settings_qrcode_url'), 'transformated_images_settings', ['qrcode_url'], unique=False)
    op.drop_index('ix_transformated_images_settings_secure_url', table_name='transformated_images_settings')
    op.create_index(op.f('ix_transformated_images_settings_secure_url'), 'transformated_images_settings', ['secure_url'], unique=False)
    op.drop_index('ix_transformated_images_settings_transformed_url', table_name='transformated_images_settings')
    op.create_index(op.f('ix_transformated_images_settings_transformed_url'), 'transformated_images_settings', ['transformed_url'], unique=False)
    op.drop_index('ix_transformated_images_settings_url', table_name='transformated_images_settings')
    op.create_index(op.f('ix_transformated_images_settings_url'), 'transformated_images_settings', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transformated_images_settings_url'), table_name='transformated_images_settings')
    op.create_index('ix_transformated_images_settings_url', 'transformated_images_settings', ['url'], unique=False)
    op.drop_index(op.f('ix_transformated_images_settings_transformed_url'), table_name='transformated_images_settings')
    op.create_index('ix_transformated_images_settings_transformed_url', 'transformated_images_settings', ['transformed_url'], unique=False)
    op.drop_index(op.f('ix_transformated_images_settings_secure_url'), table_name='transformated_images_settings')
    op.create_index('ix_transformated_images_settings_secure_url', 'transformated_images_settings', ['secure_url'], unique=False)
    op.drop_index(op.f('ix_transformated_images_settings_qrcode_url'), table_name='transformated_images_settings')
    op.create_index('ix_transformated_images_settings_qrcode_url', 'transformated_images_settings', ['qrcode_url'], unique=False)
    # ### end Alembic commands ###
