"""Init9

Revision ID: a94e41e69af7
Revises: 15f3b426f90d
Create Date: 2023-07-27 15:32:44.242238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94e41e69af7'
down_revision = '15f3b426f90d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
