"""Init2

Revision ID: bc4f5bfc2308
Revises: c59b6f02948c
Create Date: 2023-07-29 08:03:47.299232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc4f5bfc2308'
down_revision = 'c59b6f02948c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transformated_images_settings', 'transformation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformated_images_settings', sa.Column('transformation', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
