"""Init2

Revision ID: c5200c2c74aa
Revises: 5f3243574b2a
Create Date: 2023-07-25 20:40:13.848356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5200c2c74aa'
down_revision = '5f3243574b2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
