"""Init4

Revision ID: d861face407d
Revises: bc4f5bfc2308
Create Date: 2023-07-29 20:41:41.354889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd861face407d'
down_revision = 'bc4f5bfc2308'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'location')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
