"""Init2

Revision ID: d92dac71147b
Revises: e098e4e86e25
Create Date: 2023-07-28 00:03:49.134320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92dac71147b'
down_revision = 'e098e4e86e25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
