"""Init5

Revision ID: da8e057d779d
Revises: 86783f845e07
Create Date: 2023-07-26 18:35:10.579706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da8e057d779d'
down_revision = '86783f845e07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformated_images_settings', sa.Column('new_image_id', sa.Integer(), nullable=True))
    op.drop_constraint('transformated_images_settings_image_id_fkey', 'transformated_images_settings', type_='foreignkey')
    op.create_foreign_key(None, 'transformated_images_settings', 'images', ['new_image_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transformated_images_settings', 'image_id')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'crated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('crated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'created_at')
    op.add_column('transformated_images_settings', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transformated_images_settings', type_='foreignkey')
    op.create_foreign_key('transformated_images_settings_image_id_fkey', 'transformated_images_settings', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transformated_images_settings', 'new_image_id')
    # ### end Alembic commands ###
