"""Init10

Revision ID: fc80aab956f9
Revises: a94e41e69af7
Create Date: 2023-07-27 15:49:05.036207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc80aab956f9'
down_revision = 'a94e41e69af7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
